services:
  db:
    image: postgres:16-alpine
    env_file: [ ../../.env ]
    volumes:
      - ../../data/postgres:/var/lib/postgresql/data
    restart: unless-stopped

  strapi:
    image: gamecharge-strapi:prod
    env_file: [ ../../.env ]
    environment:
      NODE_ENV: production
    volumes:
      - ../../data/uploads:/app/public/uploads
    ports:
      - "127.0.0.1:1337:1337"
    depends_on:
      db:
        condition: service_started
    restart: unless-stopped